from tests.src.exception.exception import ExcecaoLancadaManualmente


class RepetirException(ExcecaoLancadaManualmente):
    pass
